language: python
python:
  - "3.6"
cache: pip
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database diarydb;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest --cov=app

#for coveralls
after_success:
  - coveralls

