version: '2'

services:
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'postgres'
      - POSTGRES_DB:'diary'
    ports:
      - "5433:5432"
    expose:
      - '5432'
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/mydiary
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - database